# Generated by Django 3.0.5 on 2020-05-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_counter',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='like_counter',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
